# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HuiZe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HuiZe
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'YYKit'
  pod 'MBProgressHUD'
  pod 'SDCycleScrollView'
  pod 'MJExtension'
  pod 'iVersion' # 版本更新
  pod 'EAIntroView' # 引导页
  pod 'JPush'
  pod 'TYPagerController' # 滑动导航
  pod 'Masonry'
#  pod 'SDAutoLayout'
#  pod 'CQCountDownButton'
  pod "RTRootNavigationController"
  pod 'JKCategories'
  pod 'IQKeyboardManager'
  pod 'JPFPSStatus', '~> 0.1.1'
  pod 'TTTAttributedLabel' #富文本的 label
#  pod 'YYCache'
  pod 'UMCShare/UI'
  pod 'UMCShare/Social/ReducedWeChat'
  pod 'UMCShare/Social/ReducedQQ'
  pod 'UMCShare/Social/ReducedSina'
  pod 'WechatOpenSDK'
  pod 'AlipaySDK-iOS'
  pod 'FORScrollViewEmptyAssistant'
  pod 'BGFMDB', '~> 2.0.13'

end
